#!/bin/sh -e
#
# Report words changed over the past week in a Git repository.  This is useful
# for tracking progress (or effort, in any case) on long writing projects.  The
# original script is from
# https://gist.github.com/MilesCranmer/5c7d86c8740219355d2dfdb184910711, and is
# modified here to be portable and easier to call.  This script accepts one
# argument, which, if passed, uses the `--since` flag to `git ref-log` to check
# for changes in a given span.  If no argument is given, the span is the last
# week.

report() {
	printf "%s\tadded: %s\tdeleted: %s\tduplicated: %s\tchanged: %s\n" $1 $2 $3 $4 $5
}

if [ "$1" = "" ]; then
	span="1.week.ago"
else
	span="$1"
fi

total=0
for sha in $(git rev-list --since=$span master | sed -e '$ d'); do
	weekday=$(git show --stat $sha | grep "^Date" |\
		sed 's/Date:\s*\(.\{3\}\).*/\1/')
	base=$(git diff --word-diff=porcelain $sha~1..$sha)
	added=$(echo "$base" | grep -e"^+[^+]" | wc -w)
	deleted=$(echo "$base" | grep -e"^-[^-]" | wc -w)
	duplicated=$(echo "$base" | grep -e"^+[^+]" -e"^-[^-]" |\
		sed -e's/.//' | sort | uniq -d | wc -w)
	changed=$((added+deleted-duplicated))
	total=$((total+changed))
	report $weekday $added $deleted $duplicated $changed
done
printf "\t\t\t\t\t\t\t  %s: %s\n" "total" $total
