#!/bin/sh -e

YEAR1=$(echo "$1" | sed 's/\(....\)\-..\-../\1/')
MONTH1=$(echo "$1" | sed 's/....\-\(..\)\-../\1/')
DAY1=$(echo "$1" | sed 's/....\-..\-\(..\)/\1/')
YEAR2=$YEAR1
MONTH2=$MONTH1
DAY2=$DAY1

if [ $# -ne 1 ]; then
	echo "Increment a passed date by one day."
	echo "inc_date YYYY-MM-DD"
	exit
fi

set -- $(cal "$MONTH1" "$YEAR1")
while test "$1" != 1; do shift; done
for MONTH_LAST; do : ; done

if [ "$MONTH_LAST" -ne "$DAY1" ]; then
	DAY2=$((DAY1 + 1))
else
	DAY2=1
	if [ "$MONTH1" -ne 12 ]; then
		MONTH2=$((MONTH1 + 1))
		DAY2=1
	else
		YEAR2=$((YEAR1 + 1))
		MONTH2=1
		DAY2=1
	fi
fi

printf '%04.0f-%02.0f-%02.0f\n' "${YEAR2}" "${MONTH2}" "${DAY2}"
