#!/bin/sh -e

# Synchronize notes with a `git` repository.

cd $HOME/Sync/notes

CHANGED="$(git status --porcelain)"

if [ -n "$CHANGED" ]; then
	git stash save
	git pull --rebase origin main
	git stash pop || true
	git add .
	git -c "user.name=JO Brickley" -c "user.email=me@jobrickley.com" commit -m "''$(date) autocommit"
	git push origin main
else
	git pull origin main
fi
